name = "sun-locke"
main = "workers-site/index.js"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[site]
bucket = ".next"

[[d1_databases]]
binding = "DB"
database_name = "sun-locke-db"
database_id = "5b51d03e-fd79-4e9d-9b6b-c69071516b67"

[vars]
SUPABASE_URL = "https://epmesvguboyffspuhvrk.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwbWVzdmd1Ym95ZmZzcHVodnJrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczNDY1MzI0NiwiZXhwIjoyMDUwMjI5MjQ2fQ.JzQmwAF035_ugMavfBT0XCsVlKHhHRqbn6pRJFimmNA" # Replace with your actual service role key
